stages:
- build
- test
- package

variables:
  GIT_DEPTH: 1
  # pin to specific docker images for build repeatability
  RUNTIME_IMAGE_TAG: "@sha256:e1995e7b44d58436ce97fbcd28a5200d8e877f476c9c4bd3e1cc394c17be050b"
  BUILDER_IMAGE_TAG: "@sha256:13933b563395cc3c6ea8bcbd95b717eb4c9fcc33c4cd7194e620713aca03180d"
  TEST_IMAGE_TAG: "@sha256:fc78e92864645317c82c4703edd5b679c3d22c24bb7253612fb350b629681637"

#******************<JOB TEMPLATES>********************#
#======================<BUILDS>=======================#
.build_node_template: &node_build
  stage: build
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    # LOW_MEMORY=OFF CLEAR_VOTES=OFF TESTNET=ON ENABLE_MIRA=OFF
    - ./ciscripts/build.sh $BUILD_OPTS
    - $CREATE_BUILD_DIRECTORY
    - mv build/install-root "$CI_JOB_NAME"
    - mv contrib/hived.run "$CI_JOB_NAME"
    - mv contrib/config-for-docker.ini "$CI_JOB_NAME"
    - $MOVE_DIR
  allow_failure: false
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - "$CI_JOB_NAME"
    expire_in: 6 hours

.testnet_node_template: &testnet_node
  variables:
    BUILD_OPTS: OFF OFF ON OFF # LOW_MEMORY=OFF CLEAR_VOTES=OFF TESTNET=ON ENABLE_MIRA=OFF
    CREATE_BUILD_DIRECTORY: mkdir -p $CI_JOB_NAME/tests/unit
    MOVE_DIR: mv build/tests/unit/chain_test build/tests/unit/plugin_test "$CI_JOB_NAME"/tests/unit #this is only for testnet node
  tags:
     - public-runner-docker

.consensus_node_template: &consensus_node
  variables:
    BUILD_OPTS: ON ON OFF OFF # LOW_MEMORY=ON CLEAR_VOTES=ON TESTNET=OFF ENABLE_MIRA=OFF
    CREATE_BUILD_DIRECTORY: mkdir $CI_JOB_NAME
  tags:
    - public-runner-docker

#=======================<TESTS>=======================#
#chain
.chain_test_template: &chaintest
  stage: test
  image: "$CI_REGISTRY_IMAGE/runtime$RUNTIME_IMAGE_TAG"
  variables:
    GIT_STRATEGY: none
  script:
    - ./testnet_node_build/tests/unit/chain_test --log_format=JUNIT --log_sink=chain_test_results.xml --log_level=error > /dev/null 2>&1
  artifacts:
    reports:
      junit: chain_test_results.xml
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker

#plugin
.plugin_test_template: &plugintest
  stage: test
  image: "$CI_REGISTRY_IMAGE/runtime$RUNTIME_IMAGE_TAG"
  variables:
    GIT_STRATEGY: none
  script:
    # note: consider using --result_code=no to force exit code 0 even when tests fail because they currently fail and I want a nice green checkmark
    - ./testnet_node_build/tests/unit/plugin_test --log_format=JUNIT --log_sink=plugin_test_results.xml --log_level=error > /dev/null 2>&1
  artifacts:
    reports:
      junit: plugin_test_results.xml
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker

#beem
.beem_test_template: &beemdhftest
  stage: test
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  variables:
    PYTHONPATH: $CI_PROJECT_DIR/tests/functional
  script:
    # boilerplate for installing latested beem
    - git clone --depth=1 --single-branch --branch dk-hybrid-operations https://gitlab.syncad.com/hive/beem.git
    - cd beem
    - python3 setup.py install --user
    - cd ..
    # stuff specific to this test
    - mkdir -p build/tests/hive-node-data
    - cd tests/functional/python_tests/dhf_tests
    - "python3 beem_dhf_tests.py initminer initminer 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n --run-hived $CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived --working-dir=$CI_PROJECT_DIR/build/tests/hive-node-data --no-erase-proposal --junit-output=beem_dhf_test.xml"
    - cd ../hived
    - "python3 hived_hybrid_operations_test.py initminer 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n --run-hived $CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived --working-dir=$CI_PROJECT_DIR/build/tests/hive-node-data"
  artifacts:
    paths:
    - tests/functional/python_tests/dhf_tests/beem_dhf_tests.log
    - tests/functional/python_tests/hived/hived_hybrid_operations_test.log
    reports:
      junit: tests/functional/python_tests/dhf_tests/beem_dhf_test.xml
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker

#list proposals
.list_proposals_tests_template: &listproposalstests
  stage: test
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  variables:
    PYTHONPATH: $CI_PROJECT_DIR/tests/functional
  script:
    # boilerplate for installing latested beem
    - git clone --depth=1 --single-branch --branch dk-hybrid-operations https://gitlab.syncad.com/hive/beem.git
    - cd beem
    - python3 setup.py install --user
    - cd ..
    # stuff specific to this test
    - mkdir -p build/tests/hive-node-data
    - cd tests/functional/python_tests/dhf_tests
    - "python3 list_proposals_tests.py initminer initminer 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n --run-hived $CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived --working-dir=$CI_PROJECT_DIR/build/tests/hive-node-data --junit-output=list_proposals_tests.xml"
  artifacts:
    paths:
    - tests/functional/python_tests/dhf_tests/hdf_list_proposal.log
    reports:
      junit: tests/functional/python_tests/dhf_tests/list_proposals_tests.xml
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker

#hived options
.hived_options_tests_template: &hivedoptstest
  stage: test
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  variables:
    PYTHONPATH: $CI_PROJECT_DIR/tests/functional
  script:
    - cd tests/functional/python_tests/hived
    - "python3 hived_options_tests.py --run-hived $CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived"
  tags:
    - public-runner-docker

#====================<PACKAGING>====================#
.packaging_nodes_template: &node_package
  stage: package
  image: docker:19.03.11
  services:
    - docker:19.03.11-dind
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - "docker build -f ciscripts/Dockerfile.ci --target=$TARGET --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE --build-arg RUNTIME_IMAGE_TAG=$RUNTIME_IMAGE_TAG --tag $CI_REGISTRY_IMAGE/$TARGET:$CI_COMMIT_SHORT_SHA ."
    - "docker push $CI_REGISTRY_IMAGE/$TARGET:$CI_COMMIT_SHORT_SHA"
    - "echo ===> the $TARGET_NAME node image for this build is: $CI_REGISTRY_IMAGE/$TARGET:$CI_COMMIT_SHORT_SHA"

#*****************</JOB TEMPLATES>********************#


#*********************<BUILDS>**********************#
#====================DEVELOPMENT=====================
#testnet_node_development_build:
#  <<: *node_build
#  <<: *testnet_node
#  environment: development
#  except:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  when: manual

consensus_build:
  <<: *node_build
  <<: *consensus_node
  environment: development
  except:
    - master
    - merge_request
    - 0.24.0
    - schedules
  when: manual

#======================STAGING=======================
#testnet_node_staging_build:
#  <<: *node_build
#  <<: *testnet_node
#  environment: staging
#  only:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules

consensus_staging_build:
  <<: *node_build
  <<: *consensus_node
  environment: staging
  only:
    - master
    - merge_request
    - 0.24.0
    - schedules

#********************</BUILDS>**********************#


#*********************<TESTS>***********************#
#====================DEVELOPMENT=====================
#development_chain_test:
#  needs:
#    - job: testnet_node_development_build
#      artifacts: true
#  <<: *chaintest
#  except:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: development

#development_plugin_test:
#  needs:
#    - job: testnet_node_development_build
#      artifacts: true
#  <<: *plugintest
#  except:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: development

#development_beem_dhf_test:
#  needs:
#    - job: testnet_node_development_build
#      artifacts: true
#  <<: *beemdhftest
#  except:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: development

#development_list_proposals_tests:
#  needs:
#    - job: testnet_node_development_build
#      artifacts: true
#  <<: *listproposalstests
#  environment: development

#develompment_hived_options_tests:
#  needs:
#    - job: testnet_node_development_build
#      artifacts: true
#  <<: *hivedoptstest
#  except:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: development


#======================STAGING=======================
#staging_chain_test:
#  needs:
#    - job: testnet_node_staging_build
#      artifacts: true
#  <<: *chaintest
#  only:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: staging

#staging_plugin_test:
#  needs:
#    - job: testnet_node_staging_build
#      artifacts: true
#  <<: *plugintest
#  only:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: staging

#staging_beem_dhf_test:
#  needs:
#    - job: testnet_node_staging_build
#      artifacts: true
#  <<: *beemdhftest
#  only:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: staging

#staging_list_proposals_tests:
#  needs:
#    - job: testnet_node_staging_build
#      artifacts: true
#  <<: *listproposalstests
#  only:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: staging

#staging_hived_options_tests:
#  needs:
#    - job: testnet_node_staging_build
#      artifacts: true
#  <<: *hivedoptstest
#  only:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
#  environment: staging

replay-test:
  stage: test
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker run -itd --name temp_container_$CI_COMMIT_SHORT_SHA -v /home/syncad/:$CI_PROJECT_DIR/replay
  needs:
    - job: consensus_build
      artifacts: true
  script:
    - rm -rf ./replay
    - mkdir ./replay

    - ls .
    - ls ./consensus_build/install-root/bin
    - ls /home/syncad/blockchain
    - cp ./consensus_build/install-root/bin/hived ./replay
    - cp ./consensus_build/install-root/bin/cli_wallet ./replay
    - cp ./consensus_build/config-for-docker.ini /home/syncad/blockchain/config.ini
    - ./ciscripts/replay.sh 100000 1000000 #benchmark interval = 100000 / stop replay at block 1000000
  artifacts:
    paths:
    - $CI_PROJECT_DIR/replay/replay.log
    reports:
    when: always
    expire_in: 6 months
  after_script:
    - docker container stop temp_container_$CI_COMMIT_SHORT_SHA
    - docker container rm temp_container_$CI_COMMIT_SHORT_SHA

#  only:
#    - master
#    - merge_request
#    - 0.24.0
#    - schedules
  tags:
    - hived-for-tests
    
#**********************</TESTS>*********************#


#********************<PACKAGING>********************#
#====================DEVELOPMENT=====================
package_consensus_node:
  <<: *node_package
  variables:
    TARGET: consensus_build
    TARGET_NAME: consensus node
  needs:
    - job: consensus_build
      artifacts: true
  environment: development
  except:
    - master
    - merge_request
    - 0.24.0
    - schedules
  tags:
    - public-runner-docker

#======================STAGING=======================
staging_package_consensus_node:
  <<: *node_package
  variables:
    TARGET: consensus_staging_build
    TARGET_NAME: consensus staging node
  needs:
    - job: consensus_staging_build
      artifacts: true
  environment: staging
  only:
    - master
    - merge_request
    - 0.24.0
    - schedules
  tags:
    - public-runner-docker

#******************</PACKAGING>*********************#
