stages:
- build
- test
- package
- data-supply
- deploy

variables:
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive
  # pin to specific docker images for build repeatability
  RUNTIME_IMAGE_TAG: "@sha256:e1995e7b44d58436ce97fbcd28a5200d8e877f476c9c4bd3e1cc394c17be050b"
  BUILDER_IMAGE_TAG: "@sha256:13933b563395cc3c6ea8bcbd95b717eb4c9fcc33c4cd7194e620713aca03180d"
  TEST_IMAGE_TAG: "@sha256:fc78e92864645317c82c4703edd5b679c3d22c24bb7253612fb350b629681637"

testnet_node_build:
  stage: build
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    # LOW_MEMORY=OFF CLEAR_VOTES=OFF TESTNET=ON
    - ./ciscripts/build.sh OFF OFF ON
    - mkdir -p "$CI_JOB_NAME"/tests/unit
    - mv build/install-root "$CI_JOB_NAME"
    - mv contrib/hived.run "$CI_JOB_NAME"
    - mv contrib/config-for-docker.ini "$CI_JOB_NAME"
    - mv build/tests/unit/chain_test build/tests/unit/plugin_test "$CI_JOB_NAME"/tests/unit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - "$CI_JOB_NAME"
    expire_in: 6 hours
  when: manual
  allow_failure: false
  tags:
     - public-runner-docker

consensus_build:
  stage: build
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    # LOW_MEMORY=ON CLEAR_VOTES=ON TESTNET=OFF
    - ./ciscripts/build.sh ON ON OFF
    - mkdir "$CI_JOB_NAME"
    - mv build/install-root "$CI_JOB_NAME"
    - mv contrib/hived.run "$CI_JOB_NAME"
    - mv contrib/config-for-docker.ini "$CI_JOB_NAME"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - "$CI_JOB_NAME"
    expire_in: 6 hours
  when: manual
  allow_failure: false
  tags:
    - public-runner-docker

chain_test:
  stage: test
  needs:
    - job: testnet_node_build
      artifacts: true
  image: "$CI_REGISTRY_IMAGE/runtime$RUNTIME_IMAGE_TAG"
  variables:
    GIT_STRATEGY: none
  script:
    - ./testnet_node_build/tests/unit/chain_test --log_format=JUNIT --log_sink=chain_test_results.xml --log_level=error > /dev/null 2>&1
  artifacts:
    reports:
      junit: chain_test_results.xml
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker

plugin_test:
  stage: test
  needs:
    - job: testnet_node_build
      artifacts: true
  image: "$CI_REGISTRY_IMAGE/runtime$RUNTIME_IMAGE_TAG"
  variables:
    GIT_STRATEGY: none
  script:
    # note: consider using --result_code=no to force exit code 0 even when tests fail because they currently fail and I want a nice green checkmark
    - ./testnet_node_build/tests/unit/plugin_test --log_format=JUNIT --log_sink=plugin_test_results.xml --log_level=error > /dev/null 2>&1
  artifacts:
    reports:
      junit: plugin_test_results.xml
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker

beem_tests:
  stage: test
  needs:
    - job: testnet_node_build
      artifacts: true
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  variables:
    PYTHONPATH: $CI_PROJECT_DIR/tests/functional
  script:
    # boilerplate for installing latested beem
    - git clone --depth=1 --single-branch --branch dk-hybrid-operations https://gitlab.syncad.com/hive/beem.git
    - cd beem
    - python3 setup.py install --user
    - cd ..
    # stuff specific to this test
    - mkdir -p build/tests/hive-node-data
    - cd tests/functional/python_tests/dhf_tests
    - "python3 beem_dhf_tests.py initminer initminer 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n --run-hived $CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived --working-dir=$CI_PROJECT_DIR/build/tests/hive-node-data --no-erase-proposal --junit-output=beem_dhf_test.xml"
    - cd ../hived
    - "python3 hived_hybrid_operations_test.py initminer 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n --run-hived $CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived --working-dir=$CI_PROJECT_DIR/build/tests/hive-node-data"
  artifacts:
    paths:
    - tests/functional/python_tests/dhf_tests/beem_dhf_tests.log
    - tests/functional/python_tests/hived/hived_hybrid_operations_test.log
    reports:
      junit: tests/functional/python_tests/dhf_tests/beem_dhf_test.xml
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker

list_proposals_tests:
  stage: test
  needs:
    - job: testnet_node_build
      artifacts: true
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  variables:
    PYTHONPATH: $CI_PROJECT_DIR/tests/functional
  script:
    # boilerplate for installing latested beem
    - git clone --depth=1 --single-branch --branch dk-hybrid-operations https://gitlab.syncad.com/hive/beem.git
    - cd beem
    - python3 setup.py install --user
    - cd ..
    # stuff specific to this test
    - mkdir -p build/tests/hive-node-data
    - cd tests/functional/python_tests/dhf_tests
    - "python3 list_proposals_tests.py initminer initminer 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n --run-hived $CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived --working-dir=$CI_PROJECT_DIR/build/tests/hive-node-data --junit-output=list_proposals_tests.xml"
  artifacts:
    paths:
    - tests/functional/python_tests/dhf_tests/hdf_list_proposal.log
    reports:
      junit: tests/functional/python_tests/dhf_tests/list_proposals_tests.xml
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker

hived_options_tests:
  stage: test
  needs:
    - job: testnet_node_build
      artifacts: true
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  variables:
    PYTHONPATH: $CI_PROJECT_DIR/tests/functional
  script:
    - cd tests/functional/python_tests/hived
    - "python3 hived_options_tests.py --run-hived $CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived"
  tags:
    - public-runner-docker

package_consensus_node:
  stage: package
  needs:
    - job: consensus_build
      artifacts: true
  image: docker:19.03.11
  services:
    - docker:19.03.11-dind
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - "docker build -f ciscripts/Dockerfile.ci --target=consensus_node --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE --build-arg RUNTIME_IMAGE_TAG=$RUNTIME_IMAGE_TAG --tag $CI_REGISTRY_IMAGE/consensus_node:$CI_COMMIT_SHORT_SHA ."
    - "docker push $CI_REGISTRY_IMAGE/consensus_node:$CI_COMMIT_SHORT_SHA"
    - "echo ===> the consensus node image for this build is: $CI_REGISTRY_IMAGE/consensus_node:$CI_COMMIT_SHORT_SHA"
  tags:
    - public-runner-docker
    
.sync_template: &sync
  stage: data-supply
  image: docker:19.03.11
  services: 
    - docker:19.03.11
  before_script:
  - echo "Blockchain will stop at $STOP_REPLAY_AT block"
  script:
    - mkdir -p ./sync/$CI_ENVIRONMENT_NAME/blockchain
    - cp ./$SOURCE_NODE/install-root/bin/hived ./sync/$CI_ENVIRONMENT_NAME
    - cp ./$SOURCE_NODE/install-root/bin/cli_wallet ./sync/$CI_ENVIRONMENT_NAME
    - cp $CONFIG_INI ./sync/$CI_ENVIRONMENT_NAME
    - mv ./sync/$CI_ENVIRONMENT_NAME/CONFIG_INI ./sync/$CI_ENVIRONMENT_NAME/config.ini
    - echo "config.ini:"
    - cat ./sync/$CI_ENVIRONMENT_NAME/config.ini
    - cp ./$SOURCE_NODE/install-root/bin/truncate_block_log ./sync/$CI_ENVIRONMENT_NAME
    - ./sync/$CI_ENVIRONMENT_NAME/truncate_block_log /blockchain/block_log $CI_PROJECT_DIR/sync/$CI_ENVIRONMENT_NAME/blockchain/block_log $STOP_REPLAY_AT
    - chmod 0777 ./ciscripts/replay.sh
    - ./ciscripts/replay.sh "$STOP_REPLAY_AT" "$HTTP_ENDPOINT" "$WS_ENDPOINT"
    
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run -itd --name temp_container_$CI_COMMIT_SHORT_SHA -v $CI_PROJECT_DIR/sync:/usr/local $CI_REGISTRY_IMAGE/consensus_node:$CI_COMMIT_SHORT_SHA
    - docker cp $CI_PROJECT_DIR/sync temp_container_$CI_COMMIT_SHORT_SHA:/usr/local/sync
  needs:
    - job: package_consensus_node
  allow_failure: false
  artifacts:
    paths:
#    - $CI_PROJECT_DIR/sync
    - $CI_PROJECT_DIR/sync/$CI_ENVIRONMENT_NAME/replay.log
    when: always
    expire_in: 6 months
  tags:
    - public-runner-docker
    - hived-for-tests

sync_staging:
  variables:
    SOURCE_NODE: consensus_build
    GIT_STRATEGY: fetch
    STOP_REPLAY_AT: 5000000 #default value, its possible to set this variable before running job
  <<: *sync
  needs:
    - job: consensus_build
      artifacts: true
  tags:
    - public-runner-docker
    - hived-for-tests
  environment: staging
  except:
    - schedules
    - master
    - merge_request
    - 0.24.0
    - development
  when: manual

sync_development:
  variables:
    SOURCE_NODE: consensus_build
    GIT_STRATEGY: fetch
    STOP_REPLAY_AT: 5000000 #default value, its possible to set this variable before running job
  <<: *sync
  needs:
    - job: consensus_build
      artifacts: true
  tags:
    - public-runner-docker
    - hived-for-tests
  environment: development
  only:
    - development
  when: manual

sync_production:
  variables:
    SOURCE_NODE: consensus_build
    GIT_STRATEGY: fetch
    STOP_REPLAY_AT: 5000000 #default value, its possible to set this variable before running job
  <<: *sync
  needs:
    - job: consensus_build
      artifacts: true
  tags:
    - public-runner-docker
    - hived-for-tests
  environment: production
  only:
    - master
    - merge_request
    - 0.24.0
  when: manual


start_deploy_staging:
  stage: deploy
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  services: 
    - docker:19.03.11
  variables:
    GIT_STRATEGY: fetch
    STOP_REPLAY_AT: 5000000 #default value, its possible to set this variable before running job
    HTTPS_ENDPOINT_PORT: 10090
    WS_ENDPOINT_PORT: 10091
  needs:
    - job: sync_staging
  before_script:
    - apt-get update -y
    - apt-get install -y netcat
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker cp temp_container_$CI_COMMIT_SHORT_SHA:/usr/local/sync $CI_PROJECT_DIR/sync 
    - docker container stop temp_container_$CI_COMMIT_SHORT_SHA
    - docker container rm temp_container_$CI_COMMIT_SHORT_SHA
    - ls ./
    - ls ./sync
    - ls ./sync/$CI_ENVIRONMENT_NAME
  script:
    - chmod 0777 ./ciscripts/staging_deploy.sh
    - ./ciscripts/staging_deploy.sh $STOP_REPLAY_AT $HTTPS_ENDPOINT_PORT $WS_ENDPOINT_PORT
  artifacts:
    paths:
      - ID.txt
      - deploy.log
  tags:
    - public-runner-docker
    - hived-for-tests
  allow_failure: false
  environment: staging
  except:
    - schedules
    - master
    - merge_request
    - 0.24.0
    - development
  when: manual

stop_deploy_staging:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  needs:
    - job: sync_staging
  script:
    - chmod 0777 ./ciscripts/stop_deploy_staging.sh
    - ./ciscripts/stop_deploy_staging.sh ./ID.txt
  environment: staging
  tags:
    - public-runner-docker
    - hived-for-tests
  allow_failure: false
  except:
    - schedules
    - master
    - merge_request
    - 0.24.0
    - development
  when: delayed
  start_in: 40 minutes

start_deploy_development:
  stage: deploy
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  variables:
    GIT_STRATEGY: fetch
    STOP_REPLAY_AT: 5000000 #default value, its possible to set this variable before running job
    HTTPS_ENDPOINT_PORT: 9090
    WS_ENDPOINT_PORT: 9091
  needs:
    - job: sync_development
  before_script:
    - apt-get update -y
    - apt-get install -y netcat
  script:
    - chmod 0777 ./ciscripts/deploy.sh
    - ./ciscripts/deploy.sh $STOP_REPLAY_AT $HTTPS_ENDPOINT_PORT $WS_ENDPOINT_PORT
  tags:
    - public-runner-docker
    - hived-for-tests
  allow_failure: false
  environment: development
  artifacts:
    paths:
      - deploy.log
  only:
    - development
  when: manual

stop_deploy_development:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  needs:
    - job: sync_development
  when: manual
  environment: development
  tags:
    - public-runner-docker
    - hived-for-tests
  allow_failure: false
  script:
    - screen -S hived-deploy-$CI_ENVIRONMENT_NAME -X quit
  only:
    - development
  when: manual

start_deploy_production:
  stage: deploy
  image: "$CI_REGISTRY_IMAGE/test$TEST_IMAGE_TAG"
  variables:
    GIT_STRATEGY: fetch
    STOP_REPLAY_AT: 5000000 #default value, its possible to set this variable before running job
    HTTPS_ENDPOINT_PORT: 8090
    WS_ENDPOINT_PORT: 8091
  needs:
    - job: sync_production
  before_script:
    - apt-get update -y
    - apt-get install -y netcat
  script:
    - chmod 0777 ./ciscripts/deploy.sh
    - ./ciscripts/deploy.sh $STOP_REPLAY_AT $HTTPS_ENDPOINT_PORT $WS_ENDPOINT_PORT
  tags:
    - public-runner-docker
    - hived-for-tests
  allow_failure: false
  environment: production
  artifacts:
    paths:
      - deploy.log
  only:
    - master
    - merge_request
    - 0.24.0
  when: manual

stop_deploy_production:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  needs:
    - job: sync_production
  when: manual
  environment: production
  tags:
    - public-runner-docker
    - hived-for-tests
  allow_failure: false
  script:
    - screen -S hived-deploy-$CI_ENVIRONMENT_NAME -X quit
  only:
    - master
    - merge_request
    - 0.24.0
  when: manual

