stages:
  - build

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
  - echo $CI_REPOSITORY_URL
  - echo $CI_PROJECT_DIR
  - mkdir -p $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME
  - echo "Working for branch" $CI_COMMIT_REF_NAME " and environment " $CI_ENVIRONMENT_SLUG
  - rm -rf $CI_BUILDS_DIR/hive/$CI_COMMIT_REF_NAME
  - git clone $CI_REPOSITORY_URL $CI_BUILDS_DIR/hive/$CI_COMMIT_REF_NAME
  - cd $CI_BUILDS_DIR/hive/$CI_COMMIT_REF_NAME
  - git checkout $CI_COMMIT_REF_NAME
  - git status
  - git submodule sync --recursive
  - git submodule update --init --recursive

after_script:
 - echo "Repository for this pipeline located on" $CI_BUILDS_DIR/hive/$CI_COMMIT_REF_NAME
 - echo "Build for this pipeline located on" $CI_BUILDS_DIR/hive/$CI_COMMIT_REF_NAME/build

staging-build:
  stage: build
  variables:
    DOCKER_BUILDKIT: 1
    LC_ALL: "C"
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - (docker build --no-cache --target consensus_node .) 2>&1 2> $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/consensus_node_build.log || { tail -n 50 $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/consensus_node_build.log; exit 1; }
    - (docker build --no-cache --target fat_node .) 2>&1 2> $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/fat_node_build.log || { tail -n 50 $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/fat_node_build.log; exit 2; }
    - (docker build --no-cache --target testnet_node_builder .) 2>&1 2> $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/testnet_node_build.log || { tail -n 50 $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/testnet_node_build.log; exit 3; }
  artifacts:
    paths:
# Warning: artifact paths *must* be subdirectory of $CI_PROJECT_DIR
    - $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/consensus_node_build.log
    - $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/fat_node_build.log
    - $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/testnet_node_build.log
    when: always
    expire_in: 1 week

  cache: {}
  tags:
    - public-runner

  allow_failure: false
  only:
   - 0.23.0
   - 0.24.0
   - develop
   - master
#  environment:
#    name: staging
#    url: http://192.168.6.144:8888/v1/chain/get_info
   

development-build:
  stage: build
  variables:
    LC_ALL: "C"
    DOCKER_BUILDKIT: 1
    DOCKER_CONFIG: $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - (docker build --no-cache --target consensus_node .) 2>&1 2> $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/consensus_node_build.log || { tail -n 50 $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/consensus_node_build.log; exit 1; }
    - (docker build --no-cache --target fat_node .) 2>&1 2> $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/fat_node_build.log || { tail -n 50 $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/fat_node_build.log; exit 2; }
    - (docker build --no-cache --target testnet_node_builder .) 2>&1 2> $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/testnet_node_build.log || { tail -n 50 $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/testnet_node_build.log; exit 3; }

  artifacts:
    paths:
# Warning: artifact paths *must* be subdirectory of $CI_PROJECT_DIR
    - $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/consensus_node_build.log
    - $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/fat_node_build.log
    - $CI_PROJECT_DIR/$CI_COMMIT_REF_NAME/testnet_node_build.log
    when: always
    expire_in: 1 week

  cache: {}
  tags:
    - public-runner

  allow_failure: false
  when: manual
  except:
   - 0.23.0
   - 0.24.0
   - develop
   - master
#  environment:  
#    name: development
#    url: http://192.168.6.144:8888/v1/chain/get_info

