
.build_node_template: &node_build
  stage: build
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    # LOW_MEMORY=OFF CLEAR_VOTES=OFF TESTNET=ON ENABLE_MIRA=OFF
    - ./ciscripts/build.sh $BUILD_OPTS
    - $CREATE_BUILD_DIRECTORY
    - mv build/install-root "$CI_JOB_NAME"
    - mv contrib/hived.run "$CI_JOB_NAME"
    - mv contrib/config-for-docker.ini "$CI_JOB_NAME"
    - $MOVE_DIR
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - "$CI_JOB_NAME"
    expire_in: 6 hours

.testnet_node_template: &testnet_node
  variables:
    BUILD_OPTS: OFF OFF ON OFF # LOW_MEMORY=OFF CLEAR_VOTES=OFF TESTNET=ON ENABLE_MIRA=OFF
    CREATE_BUILD_DIRECTORY: mkdir -p "$CI_JOB_NAME/"/tests
    MOVE_DIR: mv build/tests/chain_test build/tests/plugin_test "$CI_JOB_NAME"/tests #this is only for testnet node
  tags:
     - public-runner-docker

.consensus_node_template :&consensus_node
  variables:
    BUILD_OPTS: ON ON OFF OFF # LOW_MEMORY=ON CLEAR_VOTES=ON TESTNET=OFF ENABLE_MIRA=OFF
    CREATE_BUILD_DIRECTORY: mkdir "$CI_JOB_NAME"
  tags:
    - public-runner-docker

.fat_node_template :&fat_node
  variables:
    BUILD_OPTS: OFF OFF OFF ON # LOW_MEMORY=ON CLEAR_VOTES=ON TESTNET=OFF ENABLE_MIRA=OFF
    CREATE_BUILD_DIRECTORY: mkdir "$CI_JOB_NAME"
  tags:
    - public-runner-docker


.packaging_nodes_template: &node_package
  stage: package
  image: docker:19.03.11
  services:
    - docker:19.03.11-dind
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - "docker build -f ciscripts/Dockerfile.ci --target=$TARGET --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE --build-arg RUNTIME_IMAGE_TAG=$RUNTIME_IMAGE_TAG --tag $CI_REGISTRY_IMAGE/$TARGET:$CI_COMMIT_SHORT_SHA ."
    - "docker push $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG/$TARGET:$CI_COMMIT_SHORT_SHA"
    - "echo ===> the $TARGET_NAME node image for this build is: $CI_REGISTRY_IMAGE/$TARGET:$CI_COMMIT_SHORT_SHA"

